version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mcp-network
    volumes:
      - sanketmukadam_mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  ollama-server:
    build:
      context: ./ollama-custom
      dockerfile: ollama.Dockerfile
    container_name: ollama-server
    restart: always
    ports:
      - "11434:11434"
    networks:
      - mcp-network
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    volumes:
      - /opt/ollama/models:/root/.ollama/models
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:11434/api/tags > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s

  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: server.Dockerfile
    container_name: mcp-server
    restart: always
    ports:
      - "8000:8000"
    networks:
      - mcp-network
    depends_on:
      mongo:
        condition: service_healthy
    # Removed the redundant 'environment' block
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:8000/health > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  mcp-client:
    build:
      context: ./mcp-client
      dockerfile: client.Dockerfile
    container_name: mcp-client
    restart: always
    networks:
      - mcp-network
    depends_on:
      mcp-server:
        condition: service_healthy
      ollama-server:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SERVER_URL=http://mcp-server:8000
      - OLLAMA_URL=http://ollama-server:11434
      - INITIAL_DELAY=30
    volumes:
      - ./mcp-client/static:/app/static
      - ./mcp-client/templates:/app/templates
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:3000/health > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mcp-network
    depends_on:
      mcp-client:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/logs:/var/log/nginx
      - ./mcp-client/static:/app/static:ro

networks:
  mcp-network:
    driver: bridge

volumes:
  sanketmukadam_mongo_data:
    external: true
  sanketmukadam_ollama_data:
    external: true